version: 2
dist: releases
snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'

builds:
  - id: default
    binary: dependabot-tool-installer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

archives:
  - id: default
    builds:
      - default
    name_template: 'dependabot-tool-installer-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}{{ end }}'

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc

release:
  github:
    owner: jamiemagee
    name: dependabot-tool-installer
  prerelease: auto
