name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - uses: golangci/golangci-lint-action@v6 

      - name: Validate
        run: make validate

      - name: Build
        run: make build

      - name: Test
        run: make test
